sudo: required
services:
 - docker

before_install:
 - docker build -t lgngr/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true lgngr/react-test npm test -- --coverage

after_success:
 - echo "After success building image"
 - docker build -t lgngr/multi-client ./client
 - docker build -t lgngr/multi-nginx ./nginx
 - docker build -t lgngr/multi-server ./server
 - docker build -t lgngr/multi-worker ./worker
 # LOGIN AND PUSH IMAGES TO DOCKER HUB
 - echo "login to dockerhub"
 - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
 - echo "pusching image to dockerhub"
 - docker push lgngr/multi-client
 - docker push lgngr/multi-nginx
 - docker push lgngr/multi-server
 - docker push lgngr/multi-worker
